Check help.

In [1]:
import os
import sys
os.path.dirname(sys.executable)

'C:\\Users\\jmmir\\miniconda3\\envs\\agd-hfm_cuda'

In [2]:
sys.executable

'C:\\Users\\jmmir\\miniconda3\\envs\\agd-hfm_cuda\\python.exe'

In [1]:
0 is False

False

In [4]:
import numpy as np
np.prod(tuple(),dtype=int)

1

In [14]:
0 is False

False

In [10]:
(1,2,3)[-0:]

(1, 2, 3)

In [1]:
import sys; sys.path.insert(0,"../..")
from agd import AutomaticDifferentiation as ad
import numpy as np
import cupy as cp

In [2]:
a = ad.Sparse.identity(constant=cp.zeros((2,2)))

In [3]:
np.zeros_like(a)

hou


spAD(array([[0., 0.],
       [0., 0.]]), array([], shape=(2, 2, 0), dtype=float64), array([], shape=(2, 2, 0), dtype=int64))

In [4]:
np.full_like(a,0)

spAD(array([[0., 0.],
       [0., 0.]]), array([], shape=(2, 2, 0), dtype=float64), array([], shape=(2, 2, 0), dtype=int64))

In [2]:
import numpy as np

In [13]:
a = np.array([[1,2,2],[0,0,1]])
np.unique(a,axis=-1,return_inverse=True)

(array([[1, 2, 2],
        [0, 0, 1]]),
 array([0, 1, 2]))

In [6]:
np.unique(a)

array([0, 1, 2])

In [9]:
a[0]

array([1, 2])

## 0. Importing the required libraries

In [1]:
import agd

ModuleNotFoundError: No module named 'agd'

In [2]:
import os
from pkg_resources.extern import appdirs

os.environ.get('PYTHON_EGG_CACHE'), appdirs.user_cache_dir(appname='Python-Eggs')

(None, '/Users/mirebeau/Library/Caches/Python-Eggs')

In [8]:
os.environ.get('PYTHON_EGG_DIR')

In [7]:
from agd import Eikonal
help(Eikonal)

Help on package agd.Eikonal in agd:

NAME
    agd.Eikonal

DESCRIPTION
    # Copyright 2020 Jean-Marie Mirebeau, University Paris-Sud, CNRS, University Paris-Saclay
    # Distributed WITHOUT ANY WARRANTY. Licensed under the Apache License, Version 2.0, see http://www.apache.org/licenses/LICENSE-2.0

PACKAGE CONTENTS
    DictIn
    FileIO
    HFM_CUDA (package)
    LibraryCall
    run_detail

FUNCTIONS
    VoronoiDecomposition(arr, mode=None, *args, **kwargs)
        Calls the FileVDQ library to decompose the provided quadratic form(s),
        as based on Voronoi's first reduction of quadratic forms.
        - mode : 'cpu' or 'gpu'. Defaults to VoronoiDecomposition.default_mode
        - args,kwargs : passed to gpu decomposition method

FILE
    /Users/mirebeau/opt/miniconda3/envs/agd-hfm/lib/python3.7/site-packages/agd-0.1.12-py3.7.egg/agd/Eikonal/__init__.py




In [3]:
import sys; sys.path.insert(0,"../..")

In [2]:
import agd
from agd import Metrics
from agd import LinearParallel as lp
from agd import FiniteDifferences as fd
from agd.Metrics import Seismic
from agd import Domain
from agd import Eikonal
from agd import AutomaticDifferentiation as ad

In [4]:
help(agd)

Help on package agd:

NAME
    agd - Adaptive Grid Discretizations (agd) package.

DESCRIPTION
    This package is intented as a toolbox for discretizing and solving partial differential
    equations (PDEs), especially in the following contexts : 
    - A Cartesian grid is used for the domain discretization.
    - The PDE embeds geometric information, possibly strongly anisotropic.
    - One puts a strong emphasis on preserving the structure of the PDE 
     (monotony, causality, degenerate ellipticity, ...) at the discrete level.
    - Generic CPU/GPU programming.
    
    This package comes with an extensive suite of notebooks, which serve simultaneously the
    purposes of documentation, mathematical description, and testing. Please see 
    https://github.com/Mirebeau/AdaptiveGridDiscretizations
    
    The package is architectures around the following main components:
    - AutomaticDifferentiation : automatically compute gradients, hessians, jacobians, in 
     dense or sparse 

In [6]:
help(Metrics)

Help on package agd.Metrics in agd:

NAME
    agd.Metrics

DESCRIPTION
    # Copyright 2020 Jean-Marie Mirebeau, University Paris-Sud, CNRS, University Paris-Saclay
    # Distributed WITHOUT ANY WARRANTY. Licensed under the Apache License, Version 2.0, see http://www.apache.org/licenses/LICENSE-2.0

PACKAGE CONTENTS
    Seismic (package)
    asym_quad
    base
    diagonal
    hamiltonian
    hamiltonian_base
    isotropic
    misc
    rander
    riemann

FILE
    /Users/mirebeau/Dropbox/Programmes/Github/AdaptiveGridDiscretizations/agd/Metrics/__init__.py




In [5]:
help(ad)

Help on package agd.AutomaticDifferentiation in agd:

NAME
    agd.AutomaticDifferentiation

DESCRIPTION
    # Copyright 2020 Jean-Marie Mirebeau, University Paris-Sud, CNRS, University Paris-Saclay
    # Distributed WITHOUT ANY WARRANTY. Licensed under the Apache License, Version 2.0, see http://www.apache.org/licenses/LICENSE-2.0

PACKAGE CONTENTS
    AD_CUDA (package)
    Base
    Dense
    Dense2
    Optimization
    Reverse
    Reverse2
    Sparse
    Sparse2
    ad_generic
    ad_specific
    cupy_generic
    cupy_support
    functional
    misc

FILE
    /Users/mirebeau/Dropbox/Programmes/Github/AdaptiveGridDiscretizations/agd/AutomaticDifferentiation/__init__.py




In [3]:
Eikonal.dictIn().RunHelp()

Help on function RunSmart in module agd.Eikonal.run_detail:

RunSmart(hfmIn, co_output=None, cache=None, returns='out')
    Calls the HFM library, with pre-processing and post-processing of data.
    
    Main input : 
    - hfmIn, a dictionary like structure, containing the eikonal solver data.
    
    The C++ library embeds some help information, which can be accessed using the 
    following key:value pairs in hfmIn.
    * 'verbosity' : set to 1 or 2 to display information on run, including the defaulted keys.
     set to 0 to silence the run.
    * 'keyHelp' : set as a string of keys separated by spaces, to print help on these.
     example 'keyHelp':"seeds tips"
    
    Optional input:
    - co_output (optional) : used for reverse automatic differentiation.
    - cache (optional) : store some intermediate results to bypass computations at a later stage. 
    - returns (optional) : early aborts the run (debug purposes). ('in_raw','out_raw','out')



In [ ]:
import numpy as np
from matplotlib import pyplot as plt

In [4]:
%%javascript
IPython.OutputArea.auto_scroll_threshold = 9999;

<IPython.core.display.Javascript object>

In [30]:
help(Eikonal.dictIn)

Help on class dictIn in module agd.Eikonal.DictIn:

class dictIn(collections.abc.MutableMapping)
 |  dictIn(store=None)
 |  
 |  A dictionary like structure used as input of the Eikonal solvers.
 |  
 |  
 |  
 |  - cpu : Run algorithm on host, store data on host
 |  - cpu_transfer : Run algorithm on host, store data on device
 |  - cpu_raw : Raw call to the HFM CPU library (debug purposes)
 |  - gpu : Run algorithm on device, store data on device
 |  - gpu_transfer : Run algorithm on device, store data on host
 |  
 |  Method resolution order:
 |      dictIn
 |      collections.abc.MutableMapping
 |      collections.abc.Mapping
 |      collections.abc.Collection
 |      collections.abc.Sized
 |      collections.abc.Iterable
 |      collections.abc.Container
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  Axes(self, dims=None)
 |      The discretization points used along each coordinate axis.
 |  
 |  Grid(self, dims=None)
 |      Returns a grid of coordinates, containi

In [28]:
help(Domain.Dirichlet)

Help on class Dirichlet in module agd.Domain:

class Dirichlet(builtins.object)
 |  Dirichlet(domain, value, grid, interior_radius=None, interior=None, grid_values=0.0)
 |  
 |  Implements Dirichlet boundary conditions.
 |  When computing finite differences, values queried outside the domain interior
 |  are replaced with values obtained on the boundary along the given direction.
 |  
 |  Methods defined here:
 |  
 |  Diff2(self, u, offsets)
 |      Second order finite differences.
 |      Second order accurate in the interior, 
 |      but only first order accurate at the boundary.
 |  
 |  DiffCentered(self, u, offsets)
 |      First order finite differences, 
 |      computed using the second order accurate centered scheme.
 |      Falls back to upwind finite differences close to the boundary.
 |  
 |  DiffUpwind(self, u, offsets, reth=False)
 |      Returns first order finite differences, uses boundary values when needed.
 |  
 |  __init__(self, domain, value, grid, interior_radiu

## 1. See help

In [5]:
type(Metrics.Riemann(np.eye(2))).__name__

'Riemann'

In [23]:
m = Metrics.Riemann(np.eye(2),)

In [25]:
def f(x): print(x)
f(2)
f(2,)

2
2


In [24]:
m.m

array([[1., 0.],
       [0., 1.]])

In [9]:
print(str(m))

Riemann(array([[1., 0.],
       [0., 1.]]),)


In [12]:
print(repr(m))

Riemann(array([[1., 0.],
       [0., 1.]]),)


In [6]:
for x in m: print(x)

[[1. 0.]
 [0. 1.]]


In [22]:
repr(None)

'None'

In [21]:
help(Seismic.TTI)

Help on class TTI in module agd.Metrics.Seismic.tti:

class TTI(agd.Metrics.Seismic.implicit_base.ImplicitBase)
 |  TTI(linear, quadratic, vdim=None, *args, **kwargs)
 |  
 |  A family of reduced models, known as Tilted Transversally Anisotropic,
 |  and arising in seismic tomography.
 |  
 |  The *dual* unit ball is defined by an equation of the form
 |  l(X^2+Y^2,Z^2) + q(X^2+Y^2,Z^2) = 1,
 |  where l is linear and q is quadratic, where X,Y,Z are the coefficients of the input 
 |  vector, usually altered by a linear transformation.
 |  In two dimensions, ignore the Y^2 term.
 |  
 |  The primal norm is obtained implicitly, by solving an optimization problem.
 |  
 |  Members fields and __init__ arguments : 
 |  - linear : an array of shape (2,n1,...,nk) encoding the linear part l
 |  - quadratic : an array of shape (2,2,n1,...,nk) encoding the quadratic part q
 |  - vdim (optional) : the ambient space dimension
 |  - *args,**kwargs (optional) : passed to implicit_base
 |  
 |  Method